<html lang="en">
<head>
    <script src="/js/jquery-3.4.0.min.js"></script>
    <script type="text/javascript" src="js/jquery-clockpicker.js"></script>
    <script type="text/javascript" src="js/jquery.ubaplayer.js"></script>
<!--    <script type="text/javascript" src="js/bootstrap.min.js"></script>-->

    <title>MetaClock | 𝗧𝗛𝗘 𝗕𝗘𝗦𝗧 𝗦𝗢𝗖𝗜𝗔𝗟 𝗔𝗟𝗔𝗥𝗠 𝗖𝗟𝗢𝗖𝗞</title>

    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic+Coding" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/izimodal/1.5.1/css/iziModal.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/izimodal/1.5.1/js/iziModal.min.js" type="text/javascript"></script>

    <script src="https://apis.google.com/js/api.js"></script>
    <!--  Optimize with https://icomoon.io/app/  -->
<!--    <script defer src="https://use.fontawesome.com/releases/v5.8.1/js/all.js" integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ" crossorigin="anonymous"></script>-->


    <link rel="stylesheet" type="text/css" href="css/jquery-clockpicker.css">
<!--    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">-->
<!--    <link rel="stylesheet" type="text/css" href="css/bootstrap-theme.min.css">-->

    <link rel="stylesheet" href="/css/main.css">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">



</head>

<body>
<!--<applet code="applet.class" width="400" height="150"-->
<!--        alt="Error loading applet!"></applet>-->
<div id="ubaplayer"></div>
<svg aria-hidden="true" style="position: absolute; width: 0; height: 0; overflow: hidden;" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <symbol id="icon-question" viewBox="0 0 32 32">
            <title>question</title>
            <path d="M14 22h4v4h-4zM22 8c1.105 0 2 0.895 2 2v6l-6 4h-4v-2l6-4v-2h-10v-4h12zM16 3c-3.472 0-6.737 1.352-9.192 3.808s-3.808 5.72-3.808 9.192c0 3.472 1.352 6.737 3.808 9.192s5.72 3.808 9.192 3.808c3.472 0 6.737-1.352 9.192-3.808s3.808-5.72 3.808-9.192c0-3.472-1.352-6.737-3.808-9.192s-5.72-3.808-9.192-3.808zM16 0v0c8.837 0 16 7.163 16 16s-7.163 16-16 16c-8.837 0-16-7.163-16-16s7.163-16 16-16z"></path>
        </symbol>
        <symbol id="icon-enlarge" viewBox="0 0 32 32">
            <title>enlarge</title>
            <path d="M32 0h-13l5 5-6 6 3 3 6-6 5 5z"></path>
            <path d="M32 32v-13l-5 5-6-6-3 3 6 6-5 5z"></path>
            <path d="M0 32h13l-5-5 6-6-3-3-6 6-5-5z"></path>
            <path d="M0 0v13l5-5 6 6 3-3-6-6 5-5z"></path>
        </symbol>
        <symbol id="icon-equalizer" viewBox="0 0 32 32">
            <title>equalizer</title>
            <path d="M14 4v-0.5c0-0.825-0.675-1.5-1.5-1.5h-5c-0.825 0-1.5 0.675-1.5 1.5v0.5h-6v4h6v0.5c0 0.825 0.675 1.5 1.5 1.5h5c0.825 0 1.5-0.675 1.5-1.5v-0.5h18v-4h-18zM8 8v-4h4v4h-4zM26 13.5c0-0.825-0.675-1.5-1.5-1.5h-5c-0.825 0-1.5 0.675-1.5 1.5v0.5h-18v4h18v0.5c0 0.825 0.675 1.5 1.5 1.5h5c0.825 0 1.5-0.675 1.5-1.5v-0.5h6v-4h-6v-0.5zM20 18v-4h4v4h-4zM14 23.5c0-0.825-0.675-1.5-1.5-1.5h-5c-0.825 0-1.5 0.675-1.5 1.5v0.5h-6v4h6v0.5c0 0.825 0.675 1.5 1.5 1.5h5c0.825 0 1.5-0.675 1.5-1.5v-0.5h18v-4h-18v-0.5zM8 28v-4h4v4h-4z"></path>
        </symbol>

        <symbol id="icon-sun" viewBox="0 0 32 32">
            <title>sun</title>
            <path d="M16 26c1.105 0 2 0.895 2 2v2c0 1.105-0.895 2-2 2s-2-0.895-2-2v-2c0-1.105 0.895-2 2-2zM16 6c-1.105 0-2-0.895-2-2v-2c0-1.105 0.895-2 2-2s2 0.895 2 2v2c0 1.105-0.895 2-2 2zM30 14c1.105 0 2 0.895 2 2s-0.895 2-2 2h-2c-1.105 0-2-0.895-2-2s0.895-2 2-2h2zM6 16c0 1.105-0.895 2-2 2h-2c-1.105 0-2-0.895-2-2s0.895-2 2-2h2c1.105 0 2 0.895 2 2zM25.899 23.071l1.414 1.414c0.781 0.781 0.781 2.047 0 2.828s-2.047 0.781-2.828 0l-1.414-1.414c-0.781-0.781-0.781-2.047 0-2.828s2.047-0.781 2.828 0zM6.101 8.929l-1.414-1.414c-0.781-0.781-0.781-2.047 0-2.828s2.047-0.781 2.828 0l1.414 1.414c0.781 0.781 0.781 2.047 0 2.828s-2.047 0.781-2.828 0zM25.899 8.929c-0.781 0.781-2.047 0.781-2.828 0s-0.781-2.047 0-2.828l1.414-1.414c0.781-0.781 2.047-0.781 2.828 0s0.781 2.047 0 2.828l-1.414 1.414zM6.101 23.071c0.781-0.781 2.047-0.781 2.828 0s0.781 2.047 0 2.828l-1.414 1.414c-0.781 0.781-2.047 0.781-2.828 0s-0.781-2.047 0-2.828l1.414-1.414z"></path>
            <path d="M16 8c-4.418 0-8 3.582-8 8s3.582 8 8 8c4.418 0 8-3.582 8-8s-3.582-8-8-8zM16 21c-2.761 0-5-2.239-5-5s2.239-5 5-5 5 2.239 5 5-2.239 5-5 5z"></path>
        </symbol>
        <symbol id="icon-new-tab" viewBox="0 0 32 32">
            <title>new-tab</title>
            <path d="M6 2v24h24v-24h-24zM28 24h-20v-20h20v20zM4 28v-21l-2-2v25h25l-2-2h-21z"></path>
            <path d="M11 8l5 5-6 6 3 3 6-6 5 5v-13z"></path>
        </symbol>

        <symbol id="icon-search" viewBox="0 0 32 32">
        <title>search</title>
        <path d="M31.008 27.231l-7.58-6.447c-0.784-0.705-1.622-1.029-2.299-0.998 1.789-2.096 2.87-4.815 2.87-7.787 0-6.627-5.373-12-12-12s-12 5.373-12 12 5.373 12 12 12c2.972 0 5.691-1.081 7.787-2.87-0.031 0.677 0.293 1.515 0.998 2.299l6.447 7.58c1.104 1.226 2.907 1.33 4.007 0.23s0.997-2.903-0.23-4.007zM12 20c-4.418 0-8-3.582-8-8s3.582-8 8-8 8 3.582 8 8-3.582 8-8 8z"></path>
    </symbol>
    <symbol id="icon-alarm" viewBox="0 0 32 32">
        <title>alarm</title>
        <path d="M16 4c-7.732 0-14 6.268-14 14s6.268 14 14 14 14-6.268 14-14-6.268-14-14-14zM16 29.25c-6.213 0-11.25-5.037-11.25-11.25s5.037-11.25 11.25-11.25c6.213 0 11.25 5.037 11.25 11.25s-5.037 11.25-11.25 11.25zM29.212 8.974c0.501-0.877 0.788-1.892 0.788-2.974 0-3.314-2.686-6-6-6-1.932 0-3.65 0.913-4.747 2.331 4.121 0.851 7.663 3.287 9.96 6.643v0zM12.748 2.331c-1.097-1.418-2.816-2.331-4.748-2.331-3.314 0-6 2.686-6 6 0 1.082 0.287 2.098 0.788 2.974 2.297-3.356 5.838-5.792 9.96-6.643z"></path>
        <path d="M16 18v-8h-2v10h8v-2z"></path>
    </symbol>
    <symbol id="icon-bell" viewBox="0 0 32 32">
        <title>bell</title>
        <path d="M32.047 25c0-9-8-7-8-14 0-0.58-0.056-1.076-0.158-1.498-0.526-3.532-2.88-6.366-5.93-7.23 0.027-0.123 0.041-0.251 0.041-0.382 0-1.040-0.9-1.891-2-1.891s-2 0.851-2 1.891c0 0.131 0.014 0.258 0.041 0.382-3.421 0.969-5.966 4.416-6.039 8.545-0.001 0.060-0.002 0.121-0.002 0.183 0 7-8 5-8 14 0 2.382 5.331 4.375 12.468 4.878 0.673 1.263 2.002 2.122 3.532 2.122s2.86-0.86 3.532-2.122c7.137-0.503 12.468-2.495 12.468-4.878 0-0.007-0.001-0.014-0.001-0.021l0.048 0.021zM25.82 26.691c-1.695 0.452-3.692 0.777-5.837 0.958-0.178-2.044-1.893-3.648-3.984-3.648s-3.805 1.604-3.984 3.648c-2.144-0.18-4.142-0.506-5.837-0.958-2.332-0.622-3.447-1.318-3.855-1.691 0.408-0.372 1.523-1.068 3.855-1.691 2.712-0.724 6.199-1.122 9.82-1.122s7.109 0.398 9.82 1.122c2.332 0.622 3.447 1.318 3.855 1.691-0.408 0.372-1.523 1.068-3.855 1.691z"></path>
    </symbol>
    <symbol id="icon-music" viewBox="0 0 32 32">
        <title>music</title>
        <path d="M30 0h2v23c0 2.761-3.134 5-7 5s-7-2.239-7-5c0-2.761 3.134-5 7-5 1.959 0 3.729 0.575 5 1.501v-11.501l-16 3.556v15.444c0 2.761-3.134 5-7 5s-7-2.239-7-5c0-2.761 3.134-5 7-5 1.959 0 3.729 0.575 5 1.501v-19.501l18-4z"></path>
    </symbol>
    <symbol id="icon-info" viewBox="0 0 32 32">
        <title>info</title>
        <path d="M14 9.5c0-0.825 0.675-1.5 1.5-1.5h1c0.825 0 1.5 0.675 1.5 1.5v1c0 0.825-0.675 1.5-1.5 1.5h-1c-0.825 0-1.5-0.675-1.5-1.5v-1z"></path>
        <path d="M20 24h-8v-2h2v-6h-2v-2h6v8h2z"></path>
        <path d="M16 0c-8.837 0-16 7.163-16 16s7.163 16 16 16 16-7.163 16-16-7.163-16-16-16zM16 29c-7.18 0-13-5.82-13-13s5.82-13 13-13 13 5.82 13 13-5.82 13-13 13z"></path>
    </symbol>
    <symbol id="icon-play2" viewBox="0 0 32 32">
        <title>play2</title>
        <path d="M16 0c-8.837 0-16 7.163-16 16s7.163 16 16 16 16-7.163 16-16-7.163-16-16-16zM16 29c-7.18 0-13-5.82-13-13s5.82-13 13-13 13 5.82 13 13-5.82 13-13 13zM12 9l12 7-12 7z"></path>
    </symbol>
    <symbol id="icon-pause" viewBox="0 0 32 32">
        <title>pause</title>
        <path d="M16 0c-8.837 0-16 7.163-16 16s7.163 16 16 16 16-7.163 16-16-7.163-16-16-16zM16 29c-7.18 0-13-5.82-13-13s5.82-13 13-13 13 5.82 13 13-5.82 13-13 13zM10 10h4v12h-4zM18 10h4v12h-4z"></path>
    </symbol>
    <symbol id="icon-youtube" viewBox="0 0 32 32">
        <title>youtube</title>
        <path d="M31.681 9.6c0 0-0.313-2.206-1.275-3.175-1.219-1.275-2.581-1.281-3.206-1.356-4.475-0.325-11.194-0.325-11.194-0.325h-0.012c0 0-6.719 0-11.194 0.325-0.625 0.075-1.987 0.081-3.206 1.356-0.963 0.969-1.269 3.175-1.269 3.175s-0.319 2.588-0.319 5.181v2.425c0 2.587 0.319 5.181 0.319 5.181s0.313 2.206 1.269 3.175c1.219 1.275 2.819 1.231 3.531 1.369 2.563 0.244 10.881 0.319 10.881 0.319s6.725-0.012 11.2-0.331c0.625-0.075 1.988-0.081 3.206-1.356 0.962-0.969 1.275-3.175 1.275-3.175s0.319-2.587 0.319-5.181v-2.425c-0.006-2.588-0.325-5.181-0.325-5.181zM12.694 20.15v-8.994l8.644 4.513-8.644 4.481z"></path>
    </symbol>
</defs>
</svg>


<div id="site_container">

    <div id="birds_container env">
        <div class="bird-container bird-container--one env">
            <div class="bird bird--one"></div>
        </div>
        <div class="bird-container bird-container--two env">
            <div class="bird bird--two"></div>
        </div>
        <div class="bird-container bird-container--three env">
            <div class="bird bird--three"></div>
        </div>
        <div class="bird-container bird-container--four env">
            <div class="bird bird--four"></div>
        </div>

    </div>
    <div id="shooting_stars_container" class="env">
        <div class="shooting_star"></div>
    </div>

    <div id="stars_container" class="env">
        <div class="stars"></div>
        <div class="twinkling"></div>
    </div>

    <div id="cloud_1" class="env cloud"></div>
    <div id="cloud_2" class="env cloud"></div>
    <div id="cloud_3" class="env cloud"></div>
    <div id="cloud_4" class="env cloud"></div>
    <div id="cloud_5" class="env cloud"></div>
    <div id="cloud_6" class="env cloud"></div>

    <div class="env hidden sun_and_moon">
        <img id="img_sun" src="img/sun_large.png"/>
        <img id="img_moon" src="img/moon.svg"/>
    </div>

    <div id="night_details_container" class="night_container env">
        <div id="waking_up_text">
            <span class="hide_on_timepicker">Waking up at</span> <input type="text" id="time_to_wake_up" value="00" readonly />
        </div>
        <button class="hide_on_timepicker wu_tune setting_container" title="Wake me up before you go go go go-go"> <!-- TODO: CHANGE TITLE -->
            <svg class="icon icon-music"><use xlink:href="#icon-music"></use></svg>
            <svg class="icon icon-youtube hidden"><use xlink:href="#icon-youtube"></use></svg>
            <span class="title">Wake me up before you go go go go-go</span>
        </button>
        <button id="snooze_settings_button" class="hide_on_timepicker setting_container">
            <svg class="icon icon-bell"><use xlink:href="#icon-bell"></use></svg>
            Snooze 5 minutes

        </button>
        <button id="reset_button" class="hide_on_timepicker setting_container">
            <svg class="icon icon-sun"><use xlink:href="#icon-sun"></use></svg>
            Reset

        </button>
    </div>

<!--  TODO: Do I need that?  -->
<!--    <div id="good_night_container" class="night_container env">-->
<!--        <div id="good_night_text">-->
<!--            good night-->
<!--        </div>-->
<!--        <div id="good_night_info">-->
<!--            make sure your computer doesn't fall into sleep mode-->
<!--        </div>-->
<!--    </div>-->
    <div id="set_alarm_container" class="env hidden sun_and_moon">
        <div id="set_alarm_content">
<!--            <div class="wake_up_title">-->
<!--                Wake me up at-->
<!--            </div>-->
            <button class="wake_up_time">
                <div class="wut_inner_container">
                    <input onfocus="this.select();" onmouseup="return false;" type="text" class="wut_hours" value="07" />
                    <span class="wut_delimiter">:</span>
                    <input onfocus="this.select();" onmouseup="return false;" type="text" class="wut_minutes" value="00" />

                </div>

            </button>

            <button class="wu_tune setting_container" title="Wake me up before you go go go go-go"> <!-- TODO: CHANGE TO LIVE TEXT -->
                <svg class="icon icon-music"><use xlink:href="#icon-music"></use></svg>
                <svg class="icon icon-youtube hidden"><use xlink:href="#icon-youtube"></use></svg>
                <span class="title">Wake me up before you go go go go-go</span>
            </button>
            <div class="set_alarm_btn_container">
                <button type="button" class="set_alarm_btn btn btn-light" style="float:right">SET ALARM</button>
<!--                <button type="button" class="set_alarm_btn btn btn-light" style="float:left">SETTINGS</button>-->

                <svg class="icon icon-enlarge"><use xlink:href="#icon-enlarge"></use></svg>
                <svg class="icon icon-equalizer"><use xlink:href="#icon-equalizer"></use></svg>
                <svg class="icon icon-question"><use xlink:href="#icon-question"></use></svg>

                <!--                <div class="set_alarm_btn btn-group">-->
<!--                    <button type="button" class="btn btn-light">Action</button>-->
<!--                    <button type="button" class=" btn btn-light dropdown-toggle"-->
<!--                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--                        <span class="sr-only">Set Alarm</span>-->
<!--                    </button>-->
<!--                    <div class="dropdown-menu">-->
<!--                        <a class="dropdown-item" href="#">Action</a>-->
<!--                        <a class="dropdown-item" href="#">Another action</a>-->
<!--                        <a class="dropdown-item" href="#">Something else here</a>-->
<!--                        <div class="dropdown-divider"></div>-->
<!--                        <a class="dropdown-item" href="#">Separated link</a>-->
<!--                    </div>-->
<!--                </div>-->

            </div>
        </div>

    </div>

    <div id="wake_up_mode_tune_container" class="env_wakeup hidden sun_and_moon">
        <div class="div-round">
            <iframe id="youtube_preview_iframe" class="iframe-round" allow="autoplay; encrypted-media; fullscreen"
                    src="https://www.youtube.com/embed/Xjs6fnpPWy4?modestbranding=1&autoplay=0"></iframe>
        </div>
        <div>
<!--            Tune ... -->
        </div>

    </div>

    <div id="ground" class="env hidden"></div>
    <div id="underground" class="env hidden">
        <div id="underground_bottom"></div>
    </div>
    <div id="night_overly" class="env"></div>
    <header>
        <div id="logo">
            <a href="https://www.metaclock.com"><img src="img/logo-night.png" /></a>
        </div>
        <div id="pirsomet">
            Ad

        </div>
    </header>
</div>


<div id="tune_modal" class="ui_modal">
    <div class="modal_content">
        <nav class="tabs">
            <div class="selector" style="width: 297px;"></div>
            <a href="#" class="tab active tab_tune" tab="tab_tune">
                <svg class="icon icon-music"><use xlink:href="#icon-music"></use></svg>
                <span class="name">MetaClock Tunes</span>

            </a>
            <a href="#" class="tab tab_youtube" tab="tab_youtube">
                <svg class="icon icon-youtube"><use xlink:href="#icon-youtube"></use></svg>
                <span class="name">YouTube Video</span>
            </a>
        </nav>
        <div class="tabs_content">
            <ul>
                <li class="tab_content tab_tune_content">
                    <ul class="tunes_list ubaplayer-controls">
                       <li>
                           <a class="ubaplayer-button" media="media/Good Morning Beautiful.mp3">
                               <span class="item_title">Good Morning Beautiful</span>
                               <span class="item_desc">Steve Holy</span>
                           </a>
                       </li>
                       <li>
                           <a class="ubaplayer-button" media="media/Good Morning To You.mp3">
                               <span class="item_title">Good Morning to You</span>
                               <span class="item_desc">Unknown</span>
                           </a>
                       </li>
                       <li>
                           <a class="ubaplayer-button" media="media/FiftyYears.mp3">
                               <span class="item_title">Roja</span>
                               <span class="item_desc">SP. Balasubramaniam & Chitra</span>
                           </a>
                       </li>
                        <li>
                            <a class="ubaplayer-button" media="media/FiftyYears.mp3">
                                <span class="item_title">Kuch Kuch Hota Hai</span>
                                <span class="item_desc">Hyacinth D'Souze</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/FiftyYears.mp3">
                                <span class="item_title">Guten Morgen</span>
                                <span class="item_desc">Unknown</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/FiftyYears.mp3">
                                <span class="item_title">Sutta Na Mila</span>
                                <span class="item_desc">Unknown</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/FiftyYears.mp3">
                                <span class="item_title">Wake Up</span>
                                <span class="item_desc">Unknown Minions</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/FiftyYears.mp3">
                                <span class="item_title">Good Morning</span>
                                <span class="item_desc">Miss Li</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/FiftyYears.mp3">
                                <span class="item_title">I Feel Good</span>
                                <span class="item_desc">James Brown</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/FiftyYears.mp3">
                                <span class="item_title">Maargazhi Poovea</span>
                                <span class="item_desc">Sobha Shanker</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/FiftyYears.mp3">
                                <span class="item_title">Northeast Tradewinds</span>
                                <span class="item_desc">Mad Professor</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/FiftyYears.mp3">
                                <span class="item_title">Trumpet Morning</span>
                                <span class="item_desc">Unknown</span>
                            </a>

                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/FiftyYears.mp3">
                                <span class="item_title">Wake Me Up Before</span>
                                <span class="item_desc">Wham!</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li style="display: none" class="tab_content tab_youtube_content">
                    <input id="youtube_search" type="text" placeholder="Search YouTube or paste a link" />

                    <ul id="youtube_search_results">
                    </ul>
                </li>
            </ul>
            <div class="controls">
                <div class="buttons_container">
                    <button id="cancel_tune" type="button" class="btn btn-secondary">Cancel</button>
                    <button id="ok_tune" type="button" class="btn btn-primary">Use selected tune</button>

                </div>
            </div>
        </div>
    </div>
</div>

<!--<div id="time_modal" class="ui_modal" style="display: none">-->
<!--    <div class="modal_content">-->
<!--        <ul>-->
<!--        </ul>-->
<!--    </div>-->
<!--</div>-->

<div id="preloader">
    Preloading the preloader...
</div>
</body>
<script>
  "use strict";
  $(function () {

    // Application configuration
    window.AppSettings = {
      timer: null,
    };

    // Custom jquery methods
    $.fn.inputFilter = function (inputFilter) {
      return this.on("input keydown keyup mousedown mouseup select contextmenu drop", function () {
        if (inputFilter(this.value)) {
          this.oldValue = this.value;
          this.oldSelectionStart = this.selectionStart;
          this.oldSelectionEnd = this.selectionEnd;
        } else if (this.hasOwnProperty("oldValue")) {
          this.value = this.oldValue;
          this.setSelectionRange(this.oldSelectionStart, this.oldSelectionEnd);
        } else {

        }
      });
    };

    // Jquery elements and helper functions
    var $env = $('.env');
    var $envWakeUp = $('.env_wakeup'); // TODO
    var $tuneModal = $("#tune_modal");
    var $wakeUpTitle = $('.wake_up_title');
    var $hoursInput = $('.wut_hours');
    var $minutesInput = $('.wut_minutes');
    var $wutDelimiter = $('.wut_delimiter')[0];
    var $timeToWakeUp = $('#time_to_wake_up');
    var $resetButton = $('#reset_button');
    var $snoozeButton = $('#snooze_settings_button');

    // Helpers
    var updateDomTime = function(e) {
      var zeroBasedMinutes = e.minutes < 10 ? "0" + e.minutes : e.minutes;
      var zeroBasedHours = e.hours < 10 ? "0" + e.hours : e.hours;
      $minutesInput.val(zeroBasedMinutes);
      $hoursInput.val(zeroBasedHours);
      $timeToWakeUp.val(zeroBasedHours + ":" + zeroBasedMinutes);
    };

    // Init clock picker
    var options = function () {
      return {
        placement: 'top',
        default: $hoursInput.val() + ":" + $minutesInput.val(),
        autoclose: true,
        afterHide: function () {
        },
        beforeShow: function (e) {
          e.minutes = parseInt($('.wut_minutes').val());
          e.hours = parseInt($('.wut_hours').val());
        },
        afterShow: function (e) {
          e.minutes = parseInt($('.wut_minutes').val());
          e.hours = parseInt($('.wut_hours').val());
        },
        afterDone: function (e) {
          updateDomTime(e);
        }
      };
    };
    $hoursInput.clockpicker(Object.assign(Object.assign({}, options()), {
      afterHourSelect: function (e) {
        updateDomTime(e);
      }
    }));
    $minutesInput.clockpicker(Object.assign(Object.assign({}, options()), {
      afterShow: function () {
        $minutesInput.clockpicker('toggleView', 'minutes');
      }
    }));
    $timeToWakeUp.clockpicker(Object.assign(Object.assign({}, options()), {
      placement: 'left',
      beforeShow: function () {
        $('.hide_on_timepicker').css('opacity', 0.1);
      },
      beforeHide: function() {
        $('.hide_on_timepicker').css('opacity', 1);
      },
      afterHourSelect: function (e) {
        updateDomTime(e);
      }
    }));
    $(document).on('click', '#time_to_wake_up', function() {
      $timeToWakeUp.clockpicker('show');

    });

    var inputFilterHelper = function (maxValue, $elem) {
      return function (val) {
        if (!/^\d*$/.test(val)) {
          return false;
        }

        var intVal = parseInt(val);
        if (val.length === 0) {
          $elem.val("00");
        } else if (intVal === 0) {
          $elem.val("00");
        } else if (intVal < 10) {
          $elem.val("0" + intVal);
        } else if (intVal >= 10 && intVal <= maxValue) {
          $elem.val(intVal);
        } else if (intVal > maxValue) {
          return false;
        }

        return true;
      }
    };
    $hoursInput.inputFilter(inputFilterHelper(23, $hoursInput));
    $minutesInput.inputFilter(inputFilterHelper(59, $minutesInput));

    // Modals
    $tuneModal.iziModal({
                          title: 'Select a tune',
                          subtitle: 'You can select any tune, YouTube video or upload MP3',
                          headerColor: '#1a91d2',
                          width: 600,
                          onOpening: function () {

                            var $tabs = $('.tabs');
                            if ($tabs.data('inited')) {
                              return;
                            }

                            $tabs.data('inited', true);

                            $tabs.on("click", "a", function (e) {

                              e.preventDefault();
                              $('.tabs a').removeClass("active");
                              $(this).addClass('active');
                              var activeWidth = $(this).innerWidth();
                              var itemPos = $(this).position();
                              $(".selector").css({"left": itemPos.left + "px", "width": activeWidth + "px"});
                            });

                            $('#ok_tune').on('click', function () {
                              var $selected = $($tuneModal.find('.selected_tune')[0]);
                              var $wakeUpTune = $('.wu_tune');
                              var value = $.trim($selected.find('.item_title').text());
                              var $iconMusic = $wakeUpTune.find('.icon-music');
                              var $iconYoutube = $wakeUpTune.find('.icon-youtube');

                              $wakeUpTune.find('.title').text(value);
                              $wakeUpTune.attr('title', value);

                              if ($selected.parents('#youtube_search_results').length) {
                                $iconMusic.addClass('hidden');
                                $iconYoutube.removeClass('hidden');
                              } else {
                                $iconYoutube.addClass('hidden');
                                $iconMusic.removeClass('hidden');
                              }

                              $tuneModal.iziModal('close');
                            });

                            $('#cancel_tune').on('click', function () {
                              // TODO - change back to the previously selected tune
                              $tuneModal.iziModal('close');
                            });

                            var $youtubeSearchResults = $('#youtube_search_results');
                            $('#youtube_search').on('keyup', function (e) {
                              if (e.keyCode !== 13) {
                                return;
                              }

                              var value = $(this).val();
                              gapi.client.youtube.search.list({"part": "snippet", "maxResults": 25, "q": value, "type": "video"}).then(
                                function (response) {
                                  var result = response.result.items;
                                  $youtubeSearchResults.html("");

                                  result.forEach(function (item) {
                                    var videoId = item.id.videoId,
                                      desc = item.snippet.description,
                                      image = item.snippet.thumbnails.default.url,
                                      title = item.snippet.title;

                                    $youtubeSearchResults.append("<li videoId=\"" + videoId + "\"><div class=\"youtube_image\"><img src=\"" + image + "\"></div>" +
                                                                   "<div class=\"youtube_content\">" +
                                                                   "<span class='item_title'>" + title + "</span>" +
                                                                   "<span class='item_desc'>" + (desc ? desc : "&nbsp;") + "</span>" +
                                                                   "</div><a title='Watch on YouTube' target='blank' href='https://www.youtube" +
                                                                   ".com/watch?v=" +
                                                                   videoId +
                                                                   "'><svg title='Watch on YouTube' " +
                                                                   "class=\"icon " +
                                                                   "icon-new-tab hidden\"><use " +
                                                                   "xlink:href=\"#icon-new-tab\"></use></svg></a>" +
                                                                   "</li>");
                                  });
                                },
                                function (err) { console.error("Execute error", err); });
                            });

                          },
                          onClosing: function() {

                          }
                        });

    // Events handlers
    var resetView = function() {
      // todo
      $env.removeClass('night');
//      alert()
    };

    var chooseSnooze = function() {
      // todo
      alert()
    }
    var refreshView = function () {
      var minutes = parseInt($('.wut_minutes').val());
      var hours = parseInt($('.wut_hours').val());
      $minutesInput.clockpicker('refreshView', hours, minutes);
      $hoursInput.clockpicker('refreshView', hours, minutes);
    };
    var hourTriggerFocus = function (e) {
      if (e.target !== this && e.target !== $wutDelimiter) {
        return
      }

      setTimeout(function () {$hoursInput.trigger('focus')}, 0);
    };
    var openModal = function($modalTriggerElem) {
      return function () {
        $modalTriggerElem.iziModal('open');
      }
    };
    var loadEvent = function () {
      var $preloader = $('#preloader');
      $preloader.animate({'opacity': 0}, {
        complete: function () {
          $('#site_container').animate({'opacity': 1});
          $preloader.css('z-index', -1);
        }
      });
      $env.removeClass('hidden');

      $('.cloud').each(function () {
        var value = 50 + Math.floor(Math.random() * 400);
        $(this).css('top', value + "px");
      });

      gapi.load("client", function () {
        gapi.client.setApiKey("AIzaSyDNLiIgEPo9q_k9qIM8PgxgPh9G8buFl3Y");
        gapi.client.load("https://www.googleapis.com/discovery/v1/apis/youtube/v3/rest")
          .then(function () {},
                function (err) { console.error("Error loading GAPI client for API", err); });

      });
    };
    var tabsSwitchEvent = function () {
      var $tuneTabsContent = $('#tune_modal .tabs_content');
      var $this = $(this);
      if ($this.hasClass('active')) {
        return;
      }

      $tuneTabsContent.find('.' + $tuneModal.find('.active').attr('tab') + '_content').fadeOut(function () {
        $tuneTabsContent.find('.' + $this.attr('tab') + '_content').fadeIn(function () {
          if ($this.hasClass('tab_youtube')) {
            $('#youtube_search').focus();
          }
        });
      });
    };
    var setAlarmEvent = function () {
//        $('#stars_container').animate({'opacity': 1}, 1000);
        var hours = $hoursInput.val();
        var minutes = $minutesInput.val();

        $timeToWakeUp.val(hours + ":" + minutes);

        $env.addClass('night');

        var now = new Date(),
            tomorrow = new Date();

        tomorrow.setDate(tomorrow.getDate() + 1);
        tomorrow.setHours(hours);
        tomorrow.setMinutes(minutes);

        var secondsDiff = (Math.abs(tomorrow - now) / 36e5) * 60 * 60 * 1000;

        secondsDiff = 2 * 1000;


        window.AppSettings.timer = setTimeout(function() {
          $('#set_alarm_container').hide();
          $('#wake_up_mode_tune_container').hide().removeClass('hidden').delay(2000).fadeIn("slow");
          $env.removeClass('night');

          // TODO - Maybe a quote in the sky
        }, secondsDiff);

    };

    // Events
    $('.wut_inner_container').on('focus click', hourTriggerFocus);

    $minutesInput.on('keyup focus', refreshView);

    $hoursInput.on('keyup focus', refreshView);

    $snoozeButton.on('click', chooseSnooze);
    $resetButton.on('click', resetView);

    $(document).on('click', '.wu_tune', openModal($tuneModal));

//    $(document).on('click', '.wake_up_time', openModal($timeModal));

    $(window).on('load', loadEvent);

    $(document).on('click', '.set_alarm_btn', setAlarmEvent);

    $('.tab_youtube, .tab_tune').on('click', tabsSwitchEvent);

    $("#ubaplayer").ubaPlayer({
        codecs: [{name:"MP3", codec: 'audio/mpeg;'}]
    });

    $(document).on('click','.tunes_list li, #youtube_search_results li',function(e) {
      $('.tunes_list li, #youtube_search_results li').removeClass('selected_tune');
      $(this).addClass('selected_tune');
      if ($(this).parent('.tunes_list').length) {
        $('#ok_tune').text('Use selected tune');
      } else {
        $('#ok_tune').text('Use selected video');
      }
    });
  });

  $('#site_container').css('opacity', 0);
</script>


</html>