<html lang="en">
<head>
    <link rel="stylesheet" href="/css/main.css">

    <script src="/js/jquery-3.4.0.min.js"></script>
    <script src="/js/timeago.min.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic+Coding" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/izimodal/1.5.1/css/iziModal.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/izimodal/1.5.1/js/iziModal.min.js" type="text/javascript"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.8.1/js/all.js" integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="js/jplayer/circle.skin/circle.player.css">

    <script type="text/javascript" src="js/jplayer/jquery.transform.js"></script>
    <script type="text/javascript" src="js/jplayer/jquery.grab.js"></script>
    <script type="text/javascript" src="js/jplayer/jquery.jplayer.js"></script>
    <script type="text/javascript" src="js/jplayer/mod.csstransforms.min.js"></script>
    <script type="text/javascript" src="js/jplayer/circle.player.js"></script>


</head>

<body>

<div id="site_container">

    <div id="birds_container env">
        <div class="bird-container bird-container--one env">
            <div class="bird bird--one"></div>
        </div>
        <div class="bird-container bird-container--two env">
            <div class="bird bird--two"></div>
        </div>
        <div class="bird-container bird-container--three env">
            <div class="bird bird--three"></div>
        </div>
        <div class="bird-container bird-container--four env">
            <div class="bird bird--four"></div>
        </div>

    </div>
    <div id="shooting_stars_container" class="env">
        <div class="shooting_star"></div>
        <div class="shooting_star"></div>
        <div class="shooting_star"></div>
        <div class="shooting_star"></div>
    </div>

    <div id="stars_container">
        <div class="stars"></div>
        <div class="twinkling"></div>
    </div>

    <div id="cloud_1" class="env cloud"></div>
    <div id="cloud_2" class="env cloud"></div>
    <div id="cloud_3" class="env cloud"></div>
    <div id="cloud_4" class="env cloud"></div>
    <div id="cloud_5" class="env cloud"></div>
    <div id="cloud_6" class="env cloud"></div>


    <div id="sky"></div>
    <div class="env hidden sun_and_moon">
        <img id="img_sun" src="img/sun_large.png"/>
        <img id="img_moon" src="img/moon.svg"/>
    </div>

    <div id="good_night_container" class="env">
        <div id="good_night_text">
            All set, good night
        </div>
        <div id="good_night_info">
            make sure your computer doesn't fall into sleep mode
        </div>
    </div>
    <div id="set_alarm_container" class="env hidden sun_and_moon">
        <div id="set_alarm_content">
            <div class="wake_up_title">
                Wake me up at
            </div>
            <div class="wake_up_time">
                <div class="wut_inner_container">
                    <span class="wut_hours">07</span>
                    <span class="wut_delimiter">:</span>
                    <span class="wut_minutes">00</span>

                </div>
<!--                <ul id="time_dropdown">-->
<!--                   <li>00:00</li>-->
<!--                   <li>01:00</li>-->
<!--                   <li>02:00</li>-->
<!--                   <li>03:00</li>-->
<!--                   <li>04:00</li>-->
<!--                   <li>05:00</li>-->
<!--                   <li>06:00</li>-->
<!--                   <li>07:00</li>-->
<!--                   <li>08:00</li>-->
<!--                   <li>09:00</li>-->
<!--                   <li>10:00</li>-->
<!--                   <li>11:00</li>-->
<!--                   <li>12:00</li>-->
<!--                </ul>-->
            </div>
            <!--            <div class="wake_up_sleep_time">-->
            <!--                About 6 hours of sleep-->
            <!--            </div>-->
            <div class="wu_tune">
                <!--                <div class="wu_tune_header">Tune or YouTube</div>-->
                <div class="wu_tune_desc">
                    <div class="wu_tune_music">
                        <svg enable-background="new 0 0 50 50" height="50px" id="Layer_1" version="1.1" viewBox="0 0 50 50" width="50px"
                             xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                            <rect fill="none"
                                  height="50"
                                  width="50"/>
                            <path fill="#fff"
                                  d="M43,3v35.004c0,0-0.125,5.996-6.984,5.996C28.506,44,28,39.127,28,38c0-2.41,0.942-5.037,8-5.037c3.249,0,4-0.835,4-2.963  c0,0,0-15.463,0-16.78s-0.08-1.793-1.543-1.462c-2.517,0.569-18.957,4.133-19.613,4.29S18,16.594,18,17.75c0,2.127,0,22.997,0,25.25  s-1.742,6-8,6s-7-3.998-7-6c0-2.973,2.25-4.891,7.007-4.891C14.438,38.109,15,36.86,15,35c0-6.633,0-26.04,0-27  s0.391-1.609,1.366-1.824c1.631-0.358,24.78-5.131,24.78-5.131S43,0.622,43,3z"/>
                        </svg>
                    </div>
                    <div class="wu_tune_name_cont">
                        <div class="wu_tune_name">
                            Wacky alarm
                        </div>
                        <div class="wu_tune_edit">
                            Click to change
                        </div>
                    </div>
                </div>
            </div>
            <div class="set_alarm_btn_container">
                <a href="#" class="set_alarm_btn">SET ALARM</a>
            </div>
        </div>

    </div>
    <div id="ground" class="env hidden"></div>
    <div id="night_overly" class="env"></div>
    <header>
        <div id="logo">
            <img src="img/logo-night.png" />
        </div>
        <div id="pirsomet">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- MetaClock alarm window 728x90 -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-6056202160838970"
                 data-ad-slot="3338746476"></ins>
            <script>
              (adsbygoogle = window.adsbygoogle || []).push({});
            </script>

        </div>
    </header>
</div>


<div id="tune_modal" class="ui_modal">
    <div class="modal_content">
        <nav class="tabs">
            <div class="selector" style="width: 110px;"></div>
            <a href="#" class="active tab_tune" tab="tab_tune"><i class="fas fa-music" style="padding-right:10px;"></i>Tune</a>
            <a href="#" class="tab_youtube" tab="tab_youtube" ><i class="fab fa-youtube" style="padding-right:10px;"></i>YouTube</a>
        </nav>
        <div class="tabs_content">
            <ul>
                <li class="tab_content tab_tune_content">
                    <ul class="tunes_list">
                       <li>Song 1</li>
                       <li>Song 2</li>
                       <li>Song 3</li>
                       <li>Song 4</li>
                       <li>Song 5</li>
                       <li>Song 6</li>
                       <li>Song 7</li>
                       <li>Song 8</li>
                       <li>Song 9</li>
                       <li>Song 10</li>
                    </ul>
                    <div class="tunes_player">
                        <div id="jquery_jplayer_2" class="cp-jplayer"></div>
                        <div id="cp_container_2" class="cp-container">
                            <div class="cp-buffer-holder">
                                <div class="cp-buffer-1"></div>
                                <div class="cp-buffer-2"></div>
                            </div>
                            <div class="cp-progress-holder">
                                <div class="cp-progress-1"></div>
                                <div class="cp-progress-2"></div>
                            </div>
                            <div class="cp-circle-control"></div>
                            <ul class="cp-controls">
                                <li><a href="#" class="cp-play" tabindex="1">play</a></li>
                                <li><a href="#" class="cp-pause" style="display:none;" tabindex="1">pause</a></li>
                            </ul>
                        </div>


                    </div>
                </li>
                <li style="display: none" class="tab_content tab_youtube_content">
                    asdk youtube
                </li>
            </ul>
        </div>
    </div>
</div>

<div id="time_modal" class="ui_modal">
    <div class="modal_content">
        <ul>
        </ul>
    </div>
</div>

<div id="preloader">
    Preloading the preloader...
</div>
</body>
<script>



  "use strict";
  $(function () {


    var $env = $('.env');

    window.isNight = false;
    window.alarmSettings = {
      time: {
        hours: 7,
        minutes: 0
      }
    };

    var randomizeClouds = function () {
      $('.cloud').each(function () {
          var value = 50 + Math.floor(Math.random() * 400);
          $(this).css('top', value + "px");
        })
    };

    $(window).on('load', function () {
        $env.removeClass('hidden');

        randomizeClouds();
      });

    $('.set_alarm_btn').on('click', function () {
        if (window.isNight) {
          $('#stars_container').animate({'opacity': 0}, 1000);
          $env.removeClass('night');
        } else {
          $('#stars_container').animate({'opacity': 1}, 1000);
          $env.addClass('night')
        }

        window.isNight = !window.isNight;
      });

    var $tuneModal = $("#tune_modal");
    $tuneModal.iziModal({
      title: 'Select a tune',
      subtitle: 'You can select any tune, YouTube video or upload MP3',
      headerColor: '#1a91d2',
      width: 600,
      onOpening: function() {

        var $tabs = $('.tabs');
        if ($tabs.data('inited')) {
          return;
        }

        $tabs.data('inited', true);

        $tabs.on("click", "a", function (e) {

          e.preventDefault();
          $('.tabs a').removeClass("active");
          $(this).addClass('active');
          var activeWidth = $(this).innerWidth();
          var itemPos = $(this).position();
          $(".selector").css({"left": itemPos.left + "px", "width": activeWidth + "px"});
        });
      }
    });



    var $timeModal = $("#time_modal");
    $timeModal.iziModal({
        title: 'Select a time to wake up',
        subtitle: '',
        headerColor: '#1a91d2',
        width: 250,
        top: 250,
        onOpening: function() {

        }
    });

    ([...Array(24).keys()]).forEach(function(hour) {
      hour = hour < 10 ? "0" + hour : hour;
      $timeModal.find('ul').append('<li data-izimodal-close=\"' +  hour + ' \">' + hour + ":" + '00</li>');
      $timeModal.find('ul').append('<li data-izimodal-close=\"' +  hour + ' \">' + hour + ':' + '30</li>');
    });
    $timeModal.find('li').on('click', function() {
      var splitTime = $(this).text().split(":");
      $('.wut_hours').text(splitTime[0]);
      $('.wut_minutes').text(splitTime[1]);
    });

    $(document).on('click', '.wu_tune_desc', function () {
        $('#tune_modal').iziModal('open');
    });

    $(document).on('click', '.wake_up_time', function () {
        $('#time_modal').iziModal('open');
    });

    var $tuneTabsContent = $('#tune_modal .tabs_content');
    var $tabTuneYoutube = $('.tab_youtube, .tab_tune');

    $tabTuneYoutube.on('click', function () {
      var $this = $(this);
      if ($this.hasClass('active')) {
        return;
      }

      $tuneTabsContent.find('.' + $tuneModal.find('.active').attr('tab') + '_content').fadeOut(function () {
        $tuneTabsContent.find('.' + $this.attr('tab') + '_content').fadeIn(function() {

        });
      });
    });
    var myOtherOne = new CirclePlayer("#jquery_jplayer_2",
                                      {
                                        m4a:"http://www.jplayer.org/audio/m4a/Miaow-04-Lismore.m4a",
                                        oga:"http://www.jplayer.org/audio/ogg/Miaow-04-Lismore.ogg"
                                      }, {
                                        cssSelectorAncestor: "#cp_container_2"
                                      });
  });

  $('#site_container').css('opacity', 0);
  $(window).on('load', function () {
    $('#preloader')
      .animate({'opacity': 0}, {
        complete: function () {
          $('#site_container').animate({'opacity': 1});

//             setTimeout(function () {
//               $('html').css('overflow-y', 'auto');
//               }, 1000);
        }
      });
  });


</script>


</html>