<html lang="en">
<head>
    <script src="/js/jquery-3.4.0.min.js"></script>
    <script type="text/javascript" src="js/jquery-clockpicker.js"></script>
    <script type="text/javascript" src="js/jquery.ubaplayer.js"></script>

    <title>MetaClock | 𝗧𝗛𝗘 𝗕𝗘𝗦𝗧 𝗦𝗢𝗖𝗜𝗔𝗟 𝗔𝗟𝗔𝗥𝗠 𝗖𝗟𝗢𝗖𝗞</title>

    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic+Coding" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/izimodal/1.5.1/css/iziModal.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/izimodal/1.5.1/js/iziModal.min.js" type="text/javascript"></script>

    <script src="https://apis.google.com/js/api.js"></script>
    <!--  Optimize with https://icomoon.io/app/  -->


    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" type="text/css" href="css/jquery-clockpicker.css">

    <script>
        // App settings
        window.data = <?php echo json_encode($data); ?>;
    </script>

</head>

<body>
<div id="ubaplayer"></div>
<svg aria-hidden="true" style="position: absolute; width: 0; height: 0; overflow: hidden;" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <symbol id="icon-user" viewBox="0 0 32 32">
            <title>user</title>
            <path d="M18 22.082v-1.649c2.203-1.241 4-4.337 4-7.432 0-4.971 0-9-6-9s-6 4.029-6 9c0 3.096 1.797 6.191 4 7.432v1.649c-6.784 0.555-12 3.888-12 7.918h28c0-4.030-5.216-7.364-12-7.918z"></path>
        </symbol>
        <symbol id="icon-question" viewBox="0 0 32 32">
            <title>question</title>
            <path d="M14 22h4v4h-4zM22 8c1.105 0 2 0.895 2 2v6l-6 4h-4v-2l6-4v-2h-10v-4h12zM16 3c-3.472 0-6.737 1.352-9.192 3.808s-3.808 5.72-3.808 9.192c0 3.472 1.352 6.737 3.808 9.192s5.72 3.808 9.192 3.808c3.472 0 6.737-1.352 9.192-3.808s3.808-5.72 3.808-9.192c0-3.472-1.352-6.737-3.808-9.192s-5.72-3.808-9.192-3.808zM16 0v0c8.837 0 16 7.163 16 16s-7.163 16-16 16c-8.837 0-16-7.163-16-16s7.163-16 16-16z"></path>
        </symbol>
        <symbol id="icon-enlarge" viewBox="0 0 32 32">
            <title>enlarge</title>
            <path d="M32 0h-13l5 5-6 6 3 3 6-6 5 5z"></path>
            <path d="M32 32v-13l-5 5-6-6-3 3 6 6-5 5z"></path>
            <path d="M0 32h13l-5-5 6-6-3-3-6 6-5-5z"></path>
            <path d="M0 0v13l5-5 6 6 3-3-6-6 5-5z"></path>
        </symbol>
        <symbol id="icon-equalizer" viewBox="0 0 32 32">
            <title>equalizer</title>
            <path d="M14 4v-0.5c0-0.825-0.675-1.5-1.5-1.5h-5c-0.825 0-1.5 0.675-1.5 1.5v0.5h-6v4h6v0.5c0 0.825 0.675 1.5 1.5 1.5h5c0.825 0 1.5-0.675 1.5-1.5v-0.5h18v-4h-18zM8 8v-4h4v4h-4zM26 13.5c0-0.825-0.675-1.5-1.5-1.5h-5c-0.825 0-1.5 0.675-1.5 1.5v0.5h-18v4h18v0.5c0 0.825 0.675 1.5 1.5 1.5h5c0.825 0 1.5-0.675 1.5-1.5v-0.5h6v-4h-6v-0.5zM20 18v-4h4v4h-4zM14 23.5c0-0.825-0.675-1.5-1.5-1.5h-5c-0.825 0-1.5 0.675-1.5 1.5v0.5h-6v4h6v0.5c0 0.825 0.675 1.5 1.5 1.5h5c0.825 0 1.5-0.675 1.5-1.5v-0.5h18v-4h-18v-0.5zM8 28v-4h4v4h-4z"></path>
        </symbol>

        <symbol id="icon-sun" viewBox="0 0 32 32">
            <title>sun</title>
            <path d="M16 26c1.105 0 2 0.895 2 2v2c0 1.105-0.895 2-2 2s-2-0.895-2-2v-2c0-1.105 0.895-2 2-2zM16 6c-1.105 0-2-0.895-2-2v-2c0-1.105 0.895-2 2-2s2 0.895 2 2v2c0 1.105-0.895 2-2 2zM30 14c1.105 0 2 0.895 2 2s-0.895 2-2 2h-2c-1.105 0-2-0.895-2-2s0.895-2 2-2h2zM6 16c0 1.105-0.895 2-2 2h-2c-1.105 0-2-0.895-2-2s0.895-2 2-2h2c1.105 0 2 0.895 2 2zM25.899 23.071l1.414 1.414c0.781 0.781 0.781 2.047 0 2.828s-2.047 0.781-2.828 0l-1.414-1.414c-0.781-0.781-0.781-2.047 0-2.828s2.047-0.781 2.828 0zM6.101 8.929l-1.414-1.414c-0.781-0.781-0.781-2.047 0-2.828s2.047-0.781 2.828 0l1.414 1.414c0.781 0.781 0.781 2.047 0 2.828s-2.047 0.781-2.828 0zM25.899 8.929c-0.781 0.781-2.047 0.781-2.828 0s-0.781-2.047 0-2.828l1.414-1.414c0.781-0.781 2.047-0.781 2.828 0s0.781 2.047 0 2.828l-1.414 1.414zM6.101 23.071c0.781-0.781 2.047-0.781 2.828 0s0.781 2.047 0 2.828l-1.414 1.414c-0.781 0.781-2.047 0.781-2.828 0s-0.781-2.047 0-2.828l1.414-1.414z"></path>
            <path d="M16 8c-4.418 0-8 3.582-8 8s3.582 8 8 8c4.418 0 8-3.582 8-8s-3.582-8-8-8zM16 21c-2.761 0-5-2.239-5-5s2.239-5 5-5 5 2.239 5 5-2.239 5-5 5z"></path>
        </symbol>
        <symbol id="icon-new-tab" viewBox="0 0 32 32">
            <title>new-tab</title>
            <path d="M6 2v24h24v-24h-24zM28 24h-20v-20h20v20zM4 28v-21l-2-2v25h25l-2-2h-21z"></path>
            <path d="M11 8l5 5-6 6 3 3 6-6 5 5v-13z"></path>
        </symbol>

        <symbol id="icon-search" viewBox="0 0 32 32">
        <title>search</title>
        <path d="M31.008 27.231l-7.58-6.447c-0.784-0.705-1.622-1.029-2.299-0.998 1.789-2.096 2.87-4.815 2.87-7.787 0-6.627-5.373-12-12-12s-12 5.373-12 12 5.373 12 12 12c2.972 0 5.691-1.081 7.787-2.87-0.031 0.677 0.293 1.515 0.998 2.299l6.447 7.58c1.104 1.226 2.907 1.33 4.007 0.23s0.997-2.903-0.23-4.007zM12 20c-4.418 0-8-3.582-8-8s3.582-8 8-8 8 3.582 8 8-3.582 8-8 8z"></path>
    </symbol>
    <symbol id="icon-alarm" viewBox="0 0 32 32">
        <title>alarm</title>
        <path d="M16 4c-7.732 0-14 6.268-14 14s6.268 14 14 14 14-6.268 14-14-6.268-14-14-14zM16 29.25c-6.213 0-11.25-5.037-11.25-11.25s5.037-11.25 11.25-11.25c6.213 0 11.25 5.037 11.25 11.25s-5.037 11.25-11.25 11.25zM29.212 8.974c0.501-0.877 0.788-1.892 0.788-2.974 0-3.314-2.686-6-6-6-1.932 0-3.65 0.913-4.747 2.331 4.121 0.851 7.663 3.287 9.96 6.643v0zM12.748 2.331c-1.097-1.418-2.816-2.331-4.748-2.331-3.314 0-6 2.686-6 6 0 1.082 0.287 2.098 0.788 2.974 2.297-3.356 5.838-5.792 9.96-6.643z"></path>
        <path d="M16 18v-8h-2v10h8v-2z"></path>
    </symbol>
    <symbol id="icon-bell" viewBox="0 0 32 32">
        <title>bell</title>
        <path d="M32.047 25c0-9-8-7-8-14 0-0.58-0.056-1.076-0.158-1.498-0.526-3.532-2.88-6.366-5.93-7.23 0.027-0.123 0.041-0.251 0.041-0.382 0-1.040-0.9-1.891-2-1.891s-2 0.851-2 1.891c0 0.131 0.014 0.258 0.041 0.382-3.421 0.969-5.966 4.416-6.039 8.545-0.001 0.060-0.002 0.121-0.002 0.183 0 7-8 5-8 14 0 2.382 5.331 4.375 12.468 4.878 0.673 1.263 2.002 2.122 3.532 2.122s2.86-0.86 3.532-2.122c7.137-0.503 12.468-2.495 12.468-4.878 0-0.007-0.001-0.014-0.001-0.021l0.048 0.021zM25.82 26.691c-1.695 0.452-3.692 0.777-5.837 0.958-0.178-2.044-1.893-3.648-3.984-3.648s-3.805 1.604-3.984 3.648c-2.144-0.18-4.142-0.506-5.837-0.958-2.332-0.622-3.447-1.318-3.855-1.691 0.408-0.372 1.523-1.068 3.855-1.691 2.712-0.724 6.199-1.122 9.82-1.122s7.109 0.398 9.82 1.122c2.332 0.622 3.447 1.318 3.855 1.691-0.408 0.372-1.523 1.068-3.855 1.691z"></path>
    </symbol>
    <symbol id="icon-music" viewBox="0 0 32 32">
        <title>music</title>
        <path d="M30 0h2v23c0 2.761-3.134 5-7 5s-7-2.239-7-5c0-2.761 3.134-5 7-5 1.959 0 3.729 0.575 5 1.501v-11.501l-16 3.556v15.444c0 2.761-3.134 5-7 5s-7-2.239-7-5c0-2.761 3.134-5 7-5 1.959 0 3.729 0.575 5 1.501v-19.501l18-4z"></path>
    </symbol>
    <symbol id="icon-info" viewBox="0 0 32 32">
        <title>info</title>
        <path d="M14 9.5c0-0.825 0.675-1.5 1.5-1.5h1c0.825 0 1.5 0.675 1.5 1.5v1c0 0.825-0.675 1.5-1.5 1.5h-1c-0.825 0-1.5-0.675-1.5-1.5v-1z"></path>
        <path d="M20 24h-8v-2h2v-6h-2v-2h6v8h2z"></path>
        <path d="M16 0c-8.837 0-16 7.163-16 16s7.163 16 16 16 16-7.163 16-16-7.163-16-16-16zM16 29c-7.18 0-13-5.82-13-13s5.82-13 13-13 13 5.82 13 13-5.82 13-13 13z"></path>
    </symbol>
    <symbol id="icon-play2" viewBox="0 0 32 32">
        <title>play2</title>
        <path d="M16 0c-8.837 0-16 7.163-16 16s7.163 16 16 16 16-7.163 16-16-7.163-16-16-16zM16 29c-7.18 0-13-5.82-13-13s5.82-13 13-13 13 5.82 13 13-5.82 13-13 13zM12 9l12 7-12 7z"></path>
    </symbol>
    <symbol id="icon-pause" viewBox="0 0 32 32">
        <title>pause</title>
        <path d="M16 0c-8.837 0-16 7.163-16 16s7.163 16 16 16 16-7.163 16-16-7.163-16-16-16zM16 29c-7.18 0-13-5.82-13-13s5.82-13 13-13 13 5.82 13 13-5.82 13-13 13zM10 10h4v12h-4zM18 10h4v12h-4z"></path>
    </symbol>
    <symbol id="icon-youtube" viewBox="0 0 32 32">
        <title>youtube</title>
        <path d="M31.681 9.6c0 0-0.313-2.206-1.275-3.175-1.219-1.275-2.581-1.281-3.206-1.356-4.475-0.325-11.194-0.325-11.194-0.325h-0.012c0 0-6.719 0-11.194 0.325-0.625 0.075-1.987 0.081-3.206 1.356-0.963 0.969-1.269 3.175-1.269 3.175s-0.319 2.588-0.319 5.181v2.425c0 2.587 0.319 5.181 0.319 5.181s0.313 2.206 1.269 3.175c1.219 1.275 2.819 1.231 3.531 1.369 2.563 0.244 10.881 0.319 10.881 0.319s6.725-0.012 11.2-0.331c0.625-0.075 1.988-0.081 3.206-1.356 0.962-0.969 1.275-3.175 1.275-3.175s0.319-2.587 0.319-5.181v-2.425c-0.006-2.588-0.325-5.181-0.325-5.181zM12.694 20.15v-8.994l8.644 4.513-8.644 4.481z"></path>
    </symbol>
</defs>
</svg>


<div id="site_container">

    <div id="birds_container env">
        <div class="bird-container bird-container--one env">
            <div class="bird bird--one"></div>
        </div>
        <div class="bird-container bird-container--two env">
            <div class="bird bird--two"></div>
        </div>
        <div class="bird-container bird-container--three env">
            <div class="bird bird--three"></div>
        </div>
        <div class="bird-container bird-container--four env">
            <div class="bird bird--four"></div>
        </div>

    </div>
    <div id="shooting_stars_container" class="env">
        <div class="shooting_star"></div>
    </div>

    <div id="stars_container" class="env">
        <div class="stars"></div>
        <div class="twinkling"></div>
    </div>

    <div id="cloud_1" class="env cloud"></div>
    <div id="cloud_2" class="env cloud"></div>
    <div id="cloud_3" class="env cloud"></div>
    <div id="cloud_4" class="env cloud"></div>
    <div id="cloud_5" class="env cloud"></div>
    <div id="cloud_6" class="env cloud"></div>

    <div class="env hidden sun_and_moon">
        <img id="img_sun" src="img/sun_large.png"/>
        <img id="img_moon" src="img/moon.svg"/>
    </div>

    <div id="night_details_container" class="night_container env">
        <div id="waking_up_text">
            <span class="hide_on_timepicker">Waking up at</span> <input type="text" id="time_to_wake_up" value="00" readonly />
        </div>
        <button class="hide_on_timepicker wu_tune setting_container" title="Good Morning Beautiful">
            <svg class="icon icon-music"><use xlink:href="#icon-music"></use></svg>
            <svg class="icon icon-youtube hidden"><use xlink:href="#icon-youtube"></use></svg>
            <span class="title">Good Morning Beautiful</span>
        </button>
        <button id="snooze_settings_button" class="hide_on_timepicker setting_container">
            <svg class="icon icon-bell"><use xlink:href="#icon-bell"></use></svg>
            Snooze 5 minutes

        </button>
        <button id="reset_button" class="hide_on_timepicker setting_container">
            <svg class="icon icon-sun"><use xlink:href="#icon-sun"></use></svg>
            Reset

        </button>
    </div>


    <div id="set_alarm_container" class="env hidden sun_and_moon">
        <div id="set_alarm_content">
            <button class="wake_up_time">
                <div class="wut_inner_container">
                    <input onfocus="this.select();" onmouseup="return false;" type="text" class="wut_hours" value="07" />
                    <span class="wut_delimiter">:</span>
                    <input onfocus="this.select();" onmouseup="return false;" type="text" class="wut_minutes" value="00" />

                </div>

            </button>

            <button class="wu_tune setting_container" title="Good Morning Beautiful">
                <svg class="icon icon-music"><use xlink:href="#icon-music"></use></svg>
                <svg class="icon icon-youtube hidden"><use xlink:href="#icon-youtube"></use></svg>
                <span class="title">Good Morning Beautiful</span>
            </button>
            <div class="set_alarm_btn_container">
                <button type="button" class="set_alarm_btn btn btn-light" style="float:right">SET ALARM</button>

                <svg class="icon icon-equalizer"><use xlink:href="#icon-equalizer"></use></svg>
                <svg class="icon icon-enlarge"><use xlink:href="#icon-enlarge"></use></svg>
                <svg class="icon icon-question"><use xlink:href="#icon-question"></use></svg>

            </div>
        </div>

    </div>

    <div id="wake_up_mode_tune_container" class="env_wakeup hidden sun_and_moon">
        <div class="div-round wake_up_cont" id="wake_up_youtube_video">
            <iframe id="youtube_preview_iframe" class="iframe-round" allow="autoplay; encrypted-media; fullscreen"
                    src="https://www.youtube.com/embed/Xjs6fnpPWy4?modestbranding=1&autoplay=0"></iframe>
        </div>
        <div class="wake_up_cont ubaplayer-controls" id="wake_up_tune">
                <a class="ubaplayer-button" media="media/Good Morning Beautiful.mp3">
                    <span class="item_title"></span>
                    <span class="item_desc"></span>
                </a>
            <svg class="lds-equalizer" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid"><g transform="rotate(180 50 50)"><rect ng-attr-x="{{12.5 - config.width/2}}" y="22" ng-attr-width="{{config.width}}" height="38.4959" fill="#d2d2cb" x="7.5" width="10">
                        <animate attributeName="height" calcMode="spline" values="40;60;8;40" times="0;0.33;0.66;1" ng-attr-dur="{{config.speed}}" keySplines="0.5 0 0.5 1;0.5 0 0.5 1;0.5 0 0.5 1" repeatCount="indefinite" begin="-1.0285714285714285s" dur="1.8">
                        </animate></rect><rect ng-attr-x="{{25 - config.width/2}}" y="22" ng-attr-width="{{config.width}}" height="56.3807" fill="#4d695d" x="20" width="10">
                        <animate attributeName="height" calcMode="spline" values="40;60;8;40" times="0;0.33;0.66;1" ng-attr-dur="{{config.speed}}" keySplines="0.5 0 0.5 1;0.5 0 0.5 1;0.5 0 0.5 1" repeatCount="indefinite" begin="-1.5428571428571427s" dur="1.8">
                        </animate></rect><rect ng-attr-x="{{37.5 - config.width/2}}" y="22" ng-attr-width="{{config.width}}" height="8.07307" fill="#8ea8a1" x="32.5" width="10">
                        <animate attributeName="height" calcMode="spline" values="40;60;8;40" times="0;0.33;0.66;1" ng-attr-dur="{{config.speed}}" keySplines="0.5 0 0.5 1;0.5 0 0.5 1;0.5 0 0.5 1" repeatCount="indefinite" begin="-0.5142857142857142s" dur="1.8">
                        </animate></rect><rect ng-attr-x="{{50 - config.width/2}}" y="22" ng-attr-width="{{config.width}}" height="17.6657" fill="#ffffff" x="45" width="10">
                        <animate attributeName="height" calcMode="spline" values="40;60;8;40" times="0;0.33;0.66;1" ng-attr-dur="{{config.speed}}" keySplines="0.5 0 0.5 1;0.5 0 0.5 1;0.5 0 0.5 1" repeatCount="indefinite" begin="-0.7714285714285714s" dur="1.8">
                        </animate></rect><rect ng-attr-x="{{62.5 - config.width/2}}" y="22" ng-attr-width="{{config.width}}" height="29.9424" fill="#30b0e0" x="57.5" width="10">
                        <animate attributeName="height" calcMode="spline" values="40;60;8;40" times="0;0.33;0.66;1" ng-attr-dur="{{config.speed}}" keySplines="0.5 0 0.5 1;0.5 0 0.5 1;0.5 0 0.5 1" repeatCount="indefinite" begin="-0.2571428571428571s" dur="1.8">
                        </animate></rect><rect ng-attr-x="{{75 - config.width/2}}" y="22" ng-attr-width="{{config.width}}" height="42.1482" fill="#a1cde5" x="70" width="10">
                        <animate attributeName="height" calcMode="spline" values="40;60;8;40" times="0;0.33;0.66;1" ng-attr-dur="{{config.speed}}" keySplines="0.5 0 0.5 1;0.5 0 0.5 1;0.5 0 0.5 1" repeatCount="indefinite" begin="-1.2857142857142858s" dur="1.8">
                        </animate></rect><rect ng-attr-x="{{87.5 - config.width/2}}" y="22" ng-attr-width="{{config.width}}" height="59.0801" fill="#bfdeee" x="82.5" width="10">
                        <animate attributeName="height" calcMode="spline" values="40;60;8;40" times="0;0.33;0.66;1" ng-attr-dur="{{config.speed}}" keySplines="0.5 0 0.5 1;0.5 0 0.5 1;0.5 0 0.5 1" repeatCount="indefinite" begin="0s" dur="1.8">
                        </animate></rect></g></svg>
        </div>

    </div>

    <div id="ground" class="env hidden"></div>
    <div id="underground" class="env hidden">
        <div id="underground_bottom"></div>
    </div>
    <div id="night_overly" class="env"></div>
    <header>
        <div id="upper_header">
            <div id="logo">
                <a href="https://www.metaclock.com"><img src="img/logo-original.png" /></a>
            </div>
            <ul id="header_links">
                <li><a href="">Alarm Clock</a></li>
                <li><a href="">Blog</a></li>
                <li><a href="">Privacy Policy</a></li>
                <li><a href="">Old MetaClock</a></li>
                <li><a href="">More stuff</a></li>
                <li><a href="">More stuff</a></li>
            </ul>
            <div id="login_container">
                <div id="login_logout_link">(<a href="<?=$data['loginUrl']?>">login</a>)</div>
                <div id="login_name">
                    Guest
                </div>
                <div id="login_image"><svg class="icon icon-user"><use xlink:href="#icon-user"></div>
            </div>
        </div>

        <div id="lower_header">
            <div id="pirsomet">
                Ad
            </div>
        </div>
    </header>
</div>


<div id="tune_modal" class="ui_modal">
    <div class="modal_content">
        <nav class="tabs">
            <div class="selector" style="width: 297px;"></div>
            <a href="#" class="tab active tab_tune" tab="tab_tune">
                <svg class="icon icon-music"><use xlink:href="#icon-music"></use></svg>
                <span class="name">MetaClock Tunes</span>

            </a>
            <a href="#" class="tab tab_youtube" tab="tab_youtube">
                <svg class="icon icon-youtube"><use xlink:href="#icon-youtube"></use></svg>
                <span class="name">YouTube Video</span>
            </a>
        </nav>
        <div class="tabs_content">
            <ul>
                <li class="tab_content tab_tune_content">
                    <ul class="tunes_list ubaplayer-controls">
                       <li class="selected_tune">
                           <a class="ubaplayer-button" media="media/Good Morning Beautiful - Steve Holy.mp3">
                               <span class="item_title">Good Morning Beautiful</span>
                               <span class="item_desc">Steve Holy</span>
                           </a>
                       </li>
                       <li>
                           <a class="ubaplayer-button" media="media/Good Morning To You.mp3">
                               <span class="item_title">Good Morning to You</span>
                               <span class="item_desc">Unknown</span>
                           </a>
                       </li>
                       <li>
                           <a class="ubaplayer-button" media="media/Roja - S P Balasubramaniam & Chitra.mp3">
                               <span class="item_title">Roja</span>
                               <span class="item_desc">SP. Balasubramaniam & Chitra</span>
                           </a>
                       </li>
                        <li>
                            <a class="ubaplayer-button" media="media/Kuch Kuch Hota Hai - Hyacinth D'Souza.mp3">
                                <span class="item_title">Kuch Kuch Hota Hai</span>
                                <span class="item_desc">Hyacinth D'Souze</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/Guten Morgen.mp3">
                                <span class="item_title">Guten Morgen</span>
                                <span class="item_desc">Unknown</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/Sutta Na Mila.mp3">
                                <span class="item_title">Sutta Na Mila</span>
                                <span class="item_desc">Unknown</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/Wacky Alarm.mp3">
                                <span class="item_title">Wacky Alarm</span>
                                <span class="item_desc">Unknown Minions</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/Good Morning - Miss Li.mp3">
                                <span class="item_title">Good Morning</span>
                                <span class="item_desc">Miss Li</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/I Feel Good - James Brown.mp3">
                                <span class="item_title">I Feel Good</span>
                                <span class="item_desc">James Brown</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/Kerala Morning.mp3">
                                <span class="item_title">Kerala Morning</span>
                                <span class="item_desc">Unknown</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/Northeast Tradewinds - Mad Professor.mp3">
                                <span class="item_title">Northeast Tradewinds</span>
                                <span class="item_desc">Mad Professor</span>
                            </a>
                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/Trumpet Alarm.mp3">
                                <span class="item_title">Trumpet Alarm</span>
                                <span class="item_desc">Unknown Trumpets</span>
                            </a>

                        </li>
                        <li>
                            <a class="ubaplayer-button" media="media/Wake Me Up Before You Go-Go - Wham!.mp3">
                                <span class="item_title">Wake Me Up Before You Go-Go</span>
                                <span class="item_desc">Wham!</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li style="display: none" class="tab_content tab_youtube_content">
                    <input id="youtube_search" type="text" placeholder="Search YouTube or paste a link" />

                    <ul id="youtube_search_results">
                    </ul>
                </li>
            </ul>
            <div class="controls">
                <div class="buttons_container">
                    <button id="cancel_tune" type="button" class="btn btn-secondary">Cancel</button>
                    <button id="ok_tune" type="button" class="btn btn-primary">Use selected tune</button>

                </div>
            </div>
        </div>
    </div>
</div>

<!--<div id="time_modal" class="ui_modal" style="display: none">-->
<!--    <div class="modal_content">-->
<!--        <ul>-->
<!--        </ul>-->
<!--    </div>-->
<!--</div>-->

<div id="preloader">
    Preloading the preloader...
</div>
</body>
<script src="/js/new-main.js"></script>



</html>